version: '3.1'
services:
  stats-server:
    build: stats/stats-service
    image: stats-service-image
    container_name: stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_POSTGRES_USER=postgres
      - SPRING_DATASOURCE_POSTGRES_PASSWORD=123456

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      -"6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456

  ewm-service:
    build: ./ewm-service
    image: ewm-service-image
    container_name: ewm-service
    ports:
      - "8080:8080"

#  ewm-db:
#    image: postgres:14-alpine
